apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: q23misrh3-python 
  janus-idp.io/tekton: q23misrh3-python
  backstage.io/kubernetes-id: q23misrh3-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q23misrh3-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml